Fatal Python error: init_import_site: Failed to import the site module
Python runtime state: initialized
Traceback (most recent call last):
  File [35m"<frozen importlib._bootstrap>"[0m, line [35m1360[0m, in [35m_find_and_load[0m
  File [35m"<frozen importlib._bootstrap>"[0m, line [35m1331[0m, in [35m_find_and_load_unlocked[0m
  File [35m"<frozen importlib._bootstrap>"[0m, line [35m935[0m, in [35m_load_unlocked[0m
  File [35m"<frozen importlib._bootstrap>"[0m, line [35m1176[0m, in [35mexec_module[0m
  File [35m"<frozen site>"[0m, line [35m73[0m, in [35m<module>[0m
  File [35m"<frozen importlib._bootstrap>"[0m, line [35m1360[0m, in [35m_find_and_load[0m
  File [35m"<frozen importlib._bootstrap>"[0m, line [35m1331[0m, in [35m_find_and_load_unlocked[0m
  File [35m"<frozen importlib._bootstrap>"[0m, line [35m935[0m, in [35m_load_unlocked[0m
  File [35m"<frozen importlib._bootstrap>"[0m, line [35m1176[0m, in [35mexec_module[0m
  File [35m"<frozen os>"[0m, line [35m61[0m, in [35m<module>[0m
  File [35m"<frozen importlib._bootstrap>"[0m, line [35m1360[0m, in [35m_find_and_load[0m
  File [35m"<frozen importlib._bootstrap>"[0m, line [35m1331[0m, in [35m_find_and_load_unlocked[0m
  File [35m"<frozen importlib._bootstrap>"[0m, line [35m935[0m, in [35m_load_unlocked[0m
  File [35m"<frozen importlib._bootstrap>"[0m, line [35m1176[0m, in [35mexec_module[0m
  File [35m"<frozen posixpath>"[0m, line [35m25[0m, in [35m<module>[0m
[1;35mSystemError[0m: [35m../Objects/dictobject.c:2442: bad argument to internal function[0m
